# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0002_user_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
