# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0002_user_birthdate'),
        ('book_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login_registration.User'),
            preserve_default=False,
        ),
    ]
