# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_reviews', '0003_auto_20170525_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='login_registration.User'),
        ),
    ]
